In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', None)

In [3]:
loyalty = pd.read_csv("/home/arka/Airline_Loyalty_Analytics/data/Customer Loyalty History.csv")
flight = pd.read_csv("/home/arka/Airline_Loyalty_Analytics/data/Customer Flight Activity.csv")
calendar = pd.read_csv("/home/arka/Airline_Loyalty_Analytics/data/Calendar.csv")

In [4]:
flight = flight.drop_duplicates()

In [5]:
flight.duplicated().sum()

np.int64(0)

In [6]:
loyalty[loyalty['Salary']<0].shape

(20, 16)

In [7]:
(loyalty['Salary']<0).sum()

np.int64(20)

In [8]:
loyalty[loyalty['Salary']<0].head()

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
1082,542976,Canada,Quebec,Montreal,H2Y 4R4,Male,High School or Below,-49830.0,Divorced,Star,24127.50,2018 Promotion,2018,3,NaN,NaN
1894,959977,Canada,British Columbia,Vancouver,V5R 1W3,Female,Bachelor,-12497.0,Married,Aurora,9453.00,2018 Promotion,2018,3,NaN,NaN
2471,232755,Canada,British Columbia,Vancouver,V1E 4R6,Female,Bachelor,-46683.0,Single,Nova,4787.81,2018 Promotion,2018,3,NaN,NaN
3575,525245,Canada,British Columbia,Victoria,V10 6T5,Male,Bachelor,-45962.0,Married,Star,2402.33,2018 Promotion,2018,3,NaN,NaN
3932,603070,Canada,British Columbia,West Vancouver,V6V 8Z3,Female,Bachelor,-19325.0,Single,Star,2893.74,2018 Promotion,2018,3,NaN,NaN

In [9]:
flight[['Year','Month']].drop_duplicates().sort_values(['Year','Month'])

       Year  Month
21506  2017      1
21927  2017      2
7290   2017      3
21512  2017      4
7319   2017      5
1680   2017      6
1173   2017      7
1689   2017      8
7346   2017      9
21508  2017     10
21573  2017     11
7281   2017     12
21645  2018      1
4      2018      2
6      2018      3
5      2018      4
2      2018      5
0      2018      6
1      2018      7
7      2018      8
8      2018      9
3      2018     10
9      2018     11
10     2018     12

In [10]:
import numpy as np
loyalty.loc[
    loyalty['Salary']<0,
    'Salary'
    ] = np.nan

In [11]:
(loyalty['Salary'] < 0).sum()

np.int64(0)